LOG_LEVEL_INFO_KEY = "INFO"
LOG_LEVEL_ERROR = 1
LOD_LEVEL_DEBUG = 2
LOG_LEVEL_WARNING = 3
LOG_LEVEL_INFO = 4
LOG_LEVELS = {
    "ERROR": LOG_LEVEL_ERROR,
    "DEBUG": LOD_LEVEL_DEBUG,
    "WARNING": LOG_LEVEL_WARNING,
    LOG_LEVEL_INFO_KEY: LOG_LEVEL_INFO
}

DEFAULT_SINCE_TIME = "1h"

COLOR_SEQUENCE_PREFIX = "\x1B["

STACK_TRACE_KEY = "stackTrace"
STACK_TRACE_MARKER = "stack_trace_marker"
